### PR TITLE
Add hardware to benchmarks

### PR DESCRIPTION
**Pull request by Digitalfear117**
not 100% sure I did this part right

### CODE REVIEW

**Review by Lekuruu — COMMENTED** [review]
Sorry for the late review here :p
I think you didn't quite understand the purpose of database migrations. It's there to easily migrate to new schema versions, without having to manually do them yourselves, which can often lead to a lot of pain and suffering. That also means we should never modify existing migration data, so I'd recommend to make a new file (e.g. `013_BenchmarksHardware.up.sql`), which contains the new column `hardware`. Also please keep in mind that existing data might already be inside the benchmarks table, so make sure they get accounted for as well.

**Comment by Digitalfear117** [comment]
Updated, hopefully it's better now

**Comment by ascenttree** [comment]
lgtm

**Comment by Lekuruu** [comment]
Now the last question I have is how do we migrate existing data? Will it just be empty?

**Comment by Digitalfear117** [comment]
Yeah, I was just going to suggest we leave it null for old scores.

**Comment by Digitalfear117** [comment]
I’ll let users know about the new option, and if they want they can try to beat their old score in the new version

**Pull request closed without merging**
